In [1]:
import requests

In [2]:
URL = "https://stephen-king-api.onrender.com/api/books"
res = requests.get(URL)

In [3]:
res

In [6]:
json_data = res.json()

In [9]:
import pandas as pd

df = pd.json_normalize(json_data["data"])

df = df[["id", "Title", "Year", "ISBN"]]

In [10]:
df

    id          Title  Year               ISBN
0    1         Carrie  1974  978-0-385-08695-0
1    2    Salem's Lot  1975  978-0-385-00751-1
2    3    The Shining  1977  978-0-385-12167-5
3    4           Rage  1977  978-0-451-07645-8
4    5      The Stand  1978  978-0-385-12168-2
..  ..            ...   ...                ...
58  59   The Outsider  2018  978-1-50118-098-9
59  60      Elevation  2018  978-1-98210-231-9
60  61  The Institute  2019  978-1-98211-056-7
61  62          Later  2021  978-1-78909-649-1
62  63  Billy Summers  2021  978-1-982-17361-6

[63 rows x 4 columns]

In [35]:
Link = "https://whoa.onrender.com/whoas/random"
res = requests.get(Link)

In [36]:
res

In [37]:
json_data = res.json()

In [38]:
json_data

[{'movie': "Bill & Ted's Bogus Journey",
  'year': 1991,
  'release_date': '1991-07-19',
  'director': 'Pete Hewitt',
  'character': 'Ted Logan / Evil Ted',
  'movie_duration': '01:33:52',
  'timestamp': '00:45:10',
  'full_line': 'Whoa!',
  'current_whoa_in_movie': 18,
  'total_whoas_in_movie': 28,
  'whoa_grouping': None,
  'poster': 'https://images.ctfassets.net/a6ek464hq2lg/cJP2uvQABzZsgWj770K9y/0a2dba19352272363051b34b17fe2ebd/tldtDfLnPFOtTWp758EmIP2Hbz5.jpg',
  'video': {'1080p': 'https://videos.ctfassets.net/a6ek464hq2lg/4XhvI0U1NDgJlSijTQIDyD/8c61fefd6c1cd18b7b4a0f45174489b4/Bill___Ted-s_Bogus_Journey_18__1080p_.mp4',
   '720p': 'https://videos.ctfassets.net/a6ek464hq2lg/4KpApaqhY94ubGweHOYSFv/9f7332167f2e4f42237742f7b869529f/Bill___Ted-s_Bogus_Journey_18__720p_.mp4',
   '480p': 'https://videos.ctfassets.net/a6ek464hq2lg/1n6Anmm1Tjai1a0d3bon4H/a3e2b06768fc0a28ec01a291740e9089/Bill___Ted-s_Bogus_Journey_18__480p_.mp4',
   '360p': 'https://videos.ctfassets.net/a6ek464hq2lg/6W6pK5v1tZ1dmR86NHFUnQ/c8ce06ccfde1eddda7a3f66b7c74b54f/Bill___Ted-s_Bogus_Journey_18__360p_.mp4'},
  'audio': 'https://assets.ctfassets.net/a6ek464hq2lg/6tapSoWnCTv5UtFXglDaWF/6b6032958dc5f9d998efca5feaa9184e/Bill___Ted-s_Bogus_Journey_18.mp3'}]

In [42]:
df = pd.json_normalize(json_data[:])

In [43]:
df

,movie,year,release_date,director,character,movie_duration,timestamp,full_line,current_whoa_in_movie,total_whoas_in_movie,whoa_grouping,poster,audio,video.1080p,video.720p,video.480p,video.360p
0,Bill & Ted's Bogus Journey,1991,1991-07-19,Pete Hewitt,Ted Logan / Evil Ted,01:33:52,00:45:10,Whoa!,18,28,None,https://images.ctfassets.net/a6ek464hq2lg/cJP2...,https://assets.ctfassets.net/a6ek464hq2lg/6tap...,https://videos.ctfassets.net/a6ek464hq2lg/4Xhv...,https://videos.ctfassets.net/a6ek464hq2lg/4KpA...,https://videos.ctfassets.net/a6ek464hq2lg/1n6A...,https://videos.ctfassets.net/a6ek464hq2lg/6W6p...